-- MySQL Script generated by MySQL Workbench
-- 01/24/16 17:08:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema auctionsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auctionsystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auctionsystem` DEFAULT CHARACTER SET latin1 ;
USE `auctionsystem` ;

-- -----------------------------------------------------
-- Table `auctionsystem`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auctionsystem`.`users` ;

CREATE TABLE IF NOT EXISTS `auctionsystem`.`users` (
  `userId` INT(11) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `role` TINYINT(4) NOT NULL DEFAULT 0,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `postCode` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auctionsystem`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auctionsystem`.`categories` ;

CREATE TABLE IF NOT EXISTS `auctionsystem`.`categories` (
  `categoryId` INT(11) NOT NULL,
  `categoryName` VARCHAR(45) NOT NULL,
  `categoryDescription` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auctionsystem`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auctionsystem`.`items` ;

CREATE TABLE IF NOT EXISTS `auctionsystem`.`items` (
  `itemId` INT(11) NOT NULL,
  `categoryId` INT(11) NOT NULL,
  `itemName` VARCHAR(255) NOT NULL,
  `itemDesciption` VARCHAR(255) NOT NULL,
  `Image` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`itemId`),
  INDEX `CategoryID_idx` (`categoryId` ASC),
  CONSTRAINT `CategoryNo`
    FOREIGN KEY (`categoryId`)
    REFERENCES `auctionsystem`.`categories` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auctionsystem`.`auctions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auctionsystem`.`auctions` ;

CREATE TABLE IF NOT EXISTS `auctionsystem`.`auctions` (
  `auctionId` INT(11) NOT NULL,
  `itemId` INT(11) NOT NULL,
  `sellerId` INT(11) NOT NULL,
  `reservedPrice` DECIMAL(10,2) NOT NULL,
  `startPrice` DECIMAL(10,2) NOT NULL,
  `startTime` DATETIME NOT NULL,
  `EndTime` DATETIME NOT NULL,
  `acceptedPrice` DECIMAL(10,2) NULL,
  `condition` VARCHAR(255) NULL DEFAULT NULL,
  `viewed` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`auctionId`),
  INDEX `fk_Auctions_Items1_idx` (`itemId` ASC),
  INDEX `fk_Auction_User1_idx` (`sellerId` ASC),
  CONSTRAINT `fk_Auction_User1`
    FOREIGN KEY (`sellerId`)
    REFERENCES `auctionsystem`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Auctions_Items1`
    FOREIGN KEY (`itemId`)
    REFERENCES `auctionsystem`.`items` (`itemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auctionsystem`.`auctionwatchs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auctionsystem`.`auctionwatchs` ;

CREATE TABLE IF NOT EXISTS `auctionsystem`.`auctionwatchs` (
  `auctionWatchId` INT(11) NOT NULL,
  `auctionId` INT(11) NOT NULL,
  `userId` INT(11) NOT NULL,
  PRIMARY KEY (`auctionWatchId`),
  INDEX `AuctionID_idx` (`auctionId` ASC),
  INDEX `fk_AuctionWatch_User1_idx` (`userId` ASC),
  CONSTRAINT `AuctionNo`
    FOREIGN KEY (`auctionId`)
    REFERENCES `auctionsystem`.`auctions` (`auctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AuctionWatch_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `auctionsystem`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auctionsystem`.`bids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auctionsystem`.`bids` ;

CREATE TABLE IF NOT EXISTS `auctionsystem`.`bids` (
  `bidId` INT(11) NOT NULL,
  `auctionId` INT(11) NOT NULL,
  `buyerId` INT(11) NOT NULL,
  `bidTime` DATETIME NOT NULL,
  `bidPrice` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`bidId`),
  INDEX `fk_bids_auctions1_idx` (`auctionId` ASC),
  INDEX `fk_bids_users1_idx` (`buyerId` ASC),
  CONSTRAINT `fk_bids_auctions1`
    FOREIGN KEY (`auctionId`)
    REFERENCES `auctionsystem`.`auctions` (`auctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bids_users1`
    FOREIGN KEY (`buyerId`)
    REFERENCES `auctionsystem`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `auctionsystem`.`feedbacks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auctionsystem`.`feedbacks` ;

CREATE TABLE IF NOT EXISTS `auctionsystem`.`feedbacks` (
  `feedbackId` INT(11) NOT NULL,
  `receiver` INT(11) NOT NULL,
  `creator` INT(11) NOT NULL,
  `forAuctionId` INT(11) NULL,
  `score` INT(11) NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`feedbackId`),
  INDEX `fk_Feedback_Users1_idx` (`receiver` ASC),
  INDEX `fk_Feedback_User1_idx` (`creator` ASC),
  INDEX `fk_feedbacks_auctions1_idx` (`forAuctionId` ASC),
  CONSTRAINT `fk_Feedback_User1`
    FOREIGN KEY (`creator`)
    REFERENCES `auctionsystem`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_Users1`
    FOREIGN KEY (`receiver`)
    REFERENCES `auctionsystem`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedbacks_auctions1`
    FOREIGN KEY (`forAuctionId`)
    REFERENCES `auctionsystem`.`auctions` (`auctionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
